=== IntersectMBO/cardano-config/cardano-config/schemas/ProtocolConfig.schema.json
{
    "$id": "https://raw.githubusercontent.com/IntersectMBO/cardano-base/master/cardano-config/schemas/ProtocolConfig.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "ProtocolConfiguration",
    "properties": {
        "AlonzoGenesisFile": {
            "description": "Path to the file",
            "format": "path",
            "title": "AlonzoGenesisFile",
            "type": "string"
        },
        "AlonzoGenesisHash": {
            "description": "Hash of the file\nBlake2b_256 hash",
            "title": "AlonzoGenesisHash",
            "type": "string"
        },
        "ByronGenesisFile": {
            "description": "Path to the file",
            "format": "path",
            "title": "ByronGenesisFile",
            "type": "string"
        },
        "ByronGenesisHash": {
            "description": "Hash of the file\nBlake2b_256 hash",
            "title": "ByronGenesisHash",
            "type": "string"
        },
        "CheckpointsFile": {
            "description": "Path to the file",
            "format": "path",
            "title": "CheckpointsFile",
            "type": "string"
        },
        "CheckpointsFileHash": {
            "description": "Hash of the file\nBlake2b_256 hash",
            "title": "CheckpointsFileHash",
            "type": "string"
        },
        "ConwayGenesisFile": {
            "description": "Path to the file",
            "format": "path",
            "title": "ConwayGenesisFile",
            "type": "string"
        },
        "ConwayGenesisHash": {
            "description": "Hash of the file\nBlake2b_256 hash",
            "title": "ConwayGenesisHash",
            "type": "string"
        },
        "LastKnownBlockVersion-Alt": {
            "default": 0,
            "description": "Last known block version, alt",
            "maximum": 255,
            "minimum": 0,
            "title": "LastKnownBlockVersion-Alt",
            "type": "integer"
        },
        "LastKnownBlockVersion-Major": {
            "description": "Last known block version, major",
            "maximum": 65535,
            "minimum": 0,
            "title": "LastKnownBlockVersion-Major",
            "type": "integer"
        },
        "LastKnownBlockVersion-Minor": {
            "description": "Last known block version, minor",
            "maximum": 65535,
            "minimum": 0,
            "title": "LastKnownBlockVersion-Minor",
            "type": "integer"
        },
        "PBftSignatureThreshold": {
            "description": "Byron PBFT signature threshold",
            "title": "PBftSignatureThreshold",
            "type": "number"
        },
        "RequiresNetworkMagic": {
            "default": "RequiresNoMagic",
            "description": "Whether network magic is required",
            "enum": [
                "RequiresNoMagic",
                "RequiresMagic"
            ],
            "title": "RequiresNetworkMagic",
            "type": "string"
        },
        "ShelleyGenesisFile": {
            "description": "Path to the file",
            "format": "path",
            "title": "ShelleyGenesisFile",
            "type": "string"
        },
        "ShelleyGenesisHash": {
            "description": "Hash of the file\nBlake2b_256 hash",
            "title": "ShelleyGenesisHash",
            "type": "string"
        },
        "StartAsNonProducingNode": {
            "default": false,
            "description": "Start without producing blocks",
            "title": "StartAsNonProducingNode",
            "type": "boolean"
        }
    },
    "required": [
        "ConwayGenesisFile",
        "AlonzoGenesisFile",
        "ShelleyGenesisFile",
        "LastKnownBlockVersion-Minor",
        "LastKnownBlockVersion-Major",
        "ByronGenesisFile"
    ],
    "title": "ProtocolConfig",
    "type": "object"
}

=== IntersectMBO/cardano-config/variants/ProtocolConfig/preview.json
{
    "$schema": "https://raw.githubusercontent.com/IntersectMBO/cardano-config/main/schemas/ProtocolConfig.schema.json",
    "RequiresNetworkMagic": "RequiresMagic",
    "LastKnownBlockVersion-Major": 3,
    "LastKnownBlockVersion-Minor": 1,
    "ByronGenesisFile": "byron-genesis.json",
    "ByronGenesisHash": "83de1d7302569ad56cf9139a41e2e11346d4cb4a31c00142557b6ab3fa550761",
    "ShelleyGenesisFile": "shelley-genesis.json",
    "ShelleyGenesisHash": "363498d1024f84bb39d3fa9593ce391483cb40d479b87233f868d6e57c3a400d",
    "AlonzoGenesisFile": "alonzo-genesis.json",
    "AlonzoGenesisHash": "7e94a15f55d1e82d10f09203fa1d40f8eede58fd8066542cf6566008068ed874",
    "ConwayGenesisFile": "conway-genesis.json",
    "ConwayGenesisHash": "9cc5084f02e27210eacba47af0872e3dba8946ad9460b6072d793e1d2f3987ef",
    "CheckpointsFile": "checkpoints.json",
    "CheckpointsFileHash": "bb5056ff1ced9d68dd99720695789664f6bf6f0cb02a4010df09b813e225ac51"
}
